### ISSUE TITLE
LMP link not working

### ISSUE THREAD

**Issue by largeboii** [jrodrigv/BDAMultiplayer#4]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)
 
##### KSP and BDA Version

KSP 1.6.1

BDA 0.2 

##### OS / ENVIRONMENT
windows

##### SUMMARY

The link to the version of lmp is no longer working so i don't know what version to use. 
https://ci.appveyor.com/api/buildjobs/m3qistldf58cbo3q/artifacts/LunaMultiplayer-Debug.zip
this gets a 404 error and does not link to anything.  Help appreciated. 

##### STEPS TO REPRODUCE
N/A

**Comment by jrodrigv** [comment]
I'm working on a new release for KSP 1.8.1 maybe the best option is to wait
at the moment. But if you want to give a try in KSP 1.6.1 you can use this
https://github.com/LunaMultiplayer/LunaMultiplayer/releases/download/0.21.0/LunaMultiplayer-Debug.zip

**Comment by largeboii** [comment]
ah thanks for the update, cant wait to see the updated version for 1.8.1 Thanks for the good work
